### PR TITLE
Port to Python3, update ninja and other fixes

### PR DESCRIPTION
**Pull request by srevinsaju**
* [x] Port to Python3
* [x] Update ninja to the latest sources
* [x] Remove unwanted ninja/files : See https://github.com/srevinsaju/ninja-ide/tree/minima for the minima patches _** see NOTE_
* [x] Make the activity 'just start'
* [x] Test all the functions
* [x] Test across VMs
* [x] Final fixes 

NOTE : In the  https://github.com/srevinsaju/ninja-ide/tree/minima, `patch-20191229` includes the patches to be applied to `ninja-ide:master` in the future instances of updating the activity

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.  Well done.  Suggestions for discussion;

* [ ] remove the option to create a GTK 2 activity and the corresponding skeleton sources, as we don't have a Python 3 capable Sugar Toolkit for GTK,
* [ ] change the minimum Sugar version from 0.98 to 0.116, as that's where Python 3 support began,
* [ ] update the Hello World skeleton sources,
* [ ] update the Sugargame skeleton sources,
* [ ] a warning is in logs "This DSObject has already been destroyed!",
* [ ] trying to create an activity that already exists fails silently; a FileExistsError is in logs; better is to Alert the user.

**Comment by srevinsaju** [comment]
@quozl , WIP
> * [x]  remove the option to create a GTK 2 activity and the corresponding skeleton sources, as we don't have a Python 3 capable Sugar Toolkit for GTK,
> * [x]  change the minimum Sugar version from 0.98 to 0.116, as that's where Python 3 support began,
> * [x]  update the Hello World skeleton sources,
> * [x]  update the Sugargame skeleton sources,
> * [ ]  a warning is in logs "This DSObject has already been destroyed!",
> * [ ]  trying to create an activity that already exists fails silently; a FileExistsError is in logs; better is to Alert the user.

**Comment by srevinsaju** [comment]
@quozl, I tried a safer method to close donject, now instead of two DSObject warnings, I get only one of them, but it is not from the activity that this Warnings are raised, Please check if the same warnings come before porting.

**Comment by quozl** [comment]
Thanks.  We already found out from [another pull request](https://github.com/sugarlabs/fototoon-activity/pull/1#issuecomment-560208972) and from Python 3 release notes that object deletion timing has changed, so the DSObject warning is likely to relate to that.  I haven't seen it in Python 2.  See if the changes in the other pull request inform you.  Although the warning is from the toolkit, the warning is best placed in the toolkit for informing us whether an activity is incorrectly coded.

**Comment by srevinsaju** [comment]
@quozl , the above mentioned https://github.com/sugarlabs/fototoon-activity/pull/1#issuecomment-560208972 warning was on a chooser instance. Here the jobject was returned to the caller, but the jobject actually was destroyed in the firstplace making it impossible for the caller to use the returned jobject anymore.

**Pull request merged**
