### PR TITLE
Update metadata | Add Screenshots

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Will be adding screenshots soon.
Improved license structure.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed to 95d0d61.  Please consider;

* [ ] the .gitignore file is unrealistic and extensive; in that several patterns will never match, and the file names may eventually be used for other purposes,
* [ ] other licenses are embedded in addition to GPLv2.

**Comment by vipulgupta2048** [comment]
Thanks @quozl 
- .gitignore fixed. 
- screenshots added. 
- What files exactly, since licensecheck doesn't detect them.

```
~/S/r/develop-activity (develop|✔) $ licensecheck dist/*
dist/Develop.activity/develop_app.py: *No copyright* GPL (v2 or later)
dist/Develop.activity/setup.py: GPL (v2 or later)
dist/Develop.activity/toolbars.py: GPL (v2 or later)
dist/Develop.activity/NEWS: *No copyright* UNKNOWN
dist/Develop.activity/CREDITS: *No copyright* UNKNOWN
dist/Develop.activity/COPYING: UNKNOWN
dist/Develop.activity/symbols_tree.py: *No copyright* GPL (v2 or later)
dist/Develop.activity/PENDING: *No copyright* UNKNOWN
dist/Develop.activity/logviewer.py: GPL (v2 or later)
dist/Develop.activity/new_activity.py: GPL (v2 or later)
dist/Develop.activity/widgets.py: GPL (v2 or later)
dist/Develop.activity/README.md: *No copyright* UNKNOWN
dist/Develop.activity/sourceview_editor.py: GPL (v2 or later)
dist/sugar-commander/LICENSE: UNKNOWN
dist/sugar-commander/setup.py: GPL (v2 or later)
dist/sugar-commander/sugarcommander.py: GPL (v2 or later)
dist/sugar-commander/README.md: *No copyright* UNKNOWN
```

**Comment by vipulgupta2048** [comment]
- On the first issue, that's a good find. I am though very surprised how it could tell it was GPLv3 or later. 
There are many bugs with LicenseCheck - Notice COPYING, it should detect that file the most easily. But nothing. 

- True another bug, LicenseCheck only goes (n+1) deeper in the directory structure. As I see in further tests on my system that it's not going inside directories that are present in skeletons. I will see if there is something for recursive. Fixing Apache License.

**Comment by quozl** [comment]
> Notice COPYING, it should detect that file the most easily.  But nothing.

I disagree with you there; COPYING is not a source file, so licensecheck shouldn't detect it.

> something for recursive

"man licensecheck" talks about --recursive flag.  Sorry, I thought you knew.  You might run it again now for repositories you may have missed using it on.

> why we even have IDE files inside a activity repository

Because the activity is an IDE itself.  develop_app.py has "from ninja import introspection", so it would appear this code is correctly present.

**Comment by quozl** [comment]
Reviewed to 38df27f.  All fine except

* [ ] your change to from _NINJA-IDE_ to _this program_.

I had mentioned that while speculating why licensecheck missed it, but it turned out you weren't using --recursive.  If this was source we maintained, I'd be fine with the change, but I now find out the source is maintained in an upstream project unrelated to Sugar Labs, and they seem to like it that way, see [introspection.py](https://github.com/ninja-ide/ninja-ide/blob/e1fd45409d420a67170c49dc4a1d711a958d1705/ninja_ide/tools/introspection.py), and so merging with a later upstream version will take more time for us, and we don't really have an implied right to change the license of their work, even if it is a trivial change.

**Comment by vipulgupta2048** [comment]
Thanks for the detailed and very informative answer !! :+1: :hatching_chick: 
In short, respect the licenses and stay out the wrong.

**Comment by quozl** [comment]
To be fair, you also had several biases to deal with;
* people were effectively paying you to do work here (under GSoC), and had told you in general what to do,
* this activity bundles entire software within it that was written by other people, and what was told you no longer applied in the same way,
* you had great tools to help you, such as licensecheck, and git, that made it easy and simple.
:grin:

**Pull request merged**
